version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /pages/(.*)
  static_files: pages/\1
  upload: pages/.*

- url: /favicon.ico
  static_files: theme.css
  upload: theme.css

- url: /bower_components/(.*)
  static_files: bower_components/\1
  upload: bower_components/.*

skip_files:
- ^(.*/)?node_modules/.*